# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
- name: create certs directory
  become: yes
  file:
    path={{ kube_cert_dir }}
    state=directory
    mode=o-rwx

- name: retrieve ca.pem
  slurp:
    src: "{{kubernetes_ca_depot}}/ca.pem"
  register: ca_pem
  run_once: true
  delegate_to: "{{ groups['ca'][0] }}"

- name: register ca.pem
  set_fact:
    kube_ca_pem: "{{ ca_pem.content|b64decode }}"

- name: place ca.pem
  become: yes
  copy: content="{{ kube_ca_pem }}" dest="{{ kube_cert_dir }}/ca.pem"

- name: retrieve worker.pem
  slurp:
    src: "{{kubernetes_ca_depot}}/worker.pem"
  register: worker_pem
  run_once: true
  delegate_to: "{{ groups['ca'][0] }}"

- name: register worker.pem
  set_fact:
    kube_worker_pem: "{{ worker_pem.content|b64decode }}"

- name: place worker.pem
  become: yes
  copy: content="{{ kube_worker_pem }}" dest="{{ kube_cert_dir }}/worker.pem"

- name: retrieve worker-key.pem
  slurp:
    src: "{{kubernetes_ca_depot}}/worker-key.pem"
  register: worker_key_pem
  run_once: true
  delegate_to: "{{ groups['ca'][0] }}"

- name: register worker-key.pem
  set_fact:
    kube_worker_key_pem: "{{ worker_key_pem.content|b64decode }}"

- name: place worker-key.pem
  become: yes
  copy: content="{{ kube_worker_key_pem }}" dest="{{ kube_cert_dir }}/worker-key.pem"

- name: create manifests directory
  become: yes
  file:
    path={{ kube_manifests_dir }}
    state=directory

- name: install kubeconfig
  become: yes
  template: src=worker-kubeconfig.yaml dest={{kube_config_dir}}/worker-kubeconfig.yaml
  notify:
    - reset failed kubelet

- name: install proxy pod
  become: yes
  template: src=kube-proxy.yaml dest={{kube_manifests_dir}}/kube-proxy.yaml
  notify:
    - reset failed kubelet

- name: make fstab directory for cifs plugin
  become: yes
  file:
    path: "{{kube_volume_plugin_dir}}/fstab~cifs"
    state: directory

- name: install cifs plugin
  copy: src=cifs dest="{{kube_volume_plugin_dir}}/fstab~cifs/cifs" mode=0755
  become: true